import Head from "next/head"

import Facade from "bk/components/molecules/Facade"

export default function Home() {
  console.log("Abcde")
  return (
    <>
      <Head>
        <title>HerbCure | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Facade />
      </main>
    </>
  )
}
